Add signature v4
mdbs99/AWS pull request #13
Opened 2017-04-17 16:22 UTC by almp1

Added signature of version 4 as per link below

http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html

2017-04-23 14:57 UTC, mdbs99 reviewed
I think all these 3rd files are open source and we can use them even in private projects, right? Make sure about it, please.

2017-04-23 14:57 UTC, mdbs99 commented on src/aws_credentials.pas
> +    constructor Create(const sAccessKey, sDataStamp, sRegionName, sServiceName: string);
@almp1 please remove these prefixes "s". Here and in all the code that you did the same.

2017-04-23 14:57 UTC, mdbs99 commented on src/aws_credentials.pas
> +    function Signature: TSHA256Digest;
@almp1 why do we need this new type `TSHA256Digets`? Did you search if Synapse there is some similar?

2017-04-23 14:57 UTC, mdbs99 commented on src/aws_credentials.pas
> +function TAWSSignatureVersion4.Calculate(Request: IHTTPRequest): string;
@almp1 this method is complex. Is it possible to refactor, creating some other private methods?

2017-04-23 15:00 UTC, mdbs99 commented
@almp1 when you to make these changes, please, send a new PR to `develop` branch. I will merge these new features to `master` in the future using `develop`. Thank you!

2017-04-27 01:02 UTC, almp1 reviewed
Yes the source code copied or changed under the Mozilla license must continue under this license. However, this code can be combined into a program with proprietary files. In addition, it is possible to create a proprietary version of a code under the Mozilla license

2017-04-27 01:04 UTC, almp1 commented on src/aws_credentials.pas
> +    function Signature: TSHA256Digest;
The signature combination with hmac_sha256, was only found in synopse files

2017-04-27 12:19 UTC, mdbs99 commented
@almp1 Ok, thank you. I will merge your contributions as soon as possible as we have been talking on private.

2017-04-27 12:22 UTC, mdbs99 requested changes
@almp1 please do one more change: rename the directory "/terceiros" to "/3rd/synopse"

2017-04-28 21:23 UTC, mdbs99 approved these changes

2017-04-28 21:28 UTC, mdbs99 commented
@almp1 thanks. I merged into `develop` branch.

2017-04-28 21:28 UTC, closed without merging